data:
    feature_columns: ['h', 'omch2', 'As1e9', 'ns', 'log10kh',]
    label_columns: ['log10Pk',]
    batch_size: 256
    num_workers: 10
    shuffle: true
    train_data_path: "./data/Pk_train.csv"
    val_data_path: "./data/Pk_val.csv"
    test_data_path: "./data/Pk_test.csv"
    feature_scaler: 'StandardScaler'
    label_scaler: 'StandardScaler'

model:
    hidden_dims: [128, 64,]
    activation: 'gelu'
    loss: 'L1Loss'
    dropout: 0.
    learning_rate: 1.e-2
    weight_decay: 5.e-6
    batch_norm: false
    type: FullyConnected

training:
    gpus: [0]
    max_epochs: 1500
    stochastic_weight_avg: true
    default_root_dir: "./emulators/"

